version: '3.8'
services:
  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    volumes:
      - "./redis_data:/data"
    ports:
      - 6379
    networks:
      - default

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true
