---
- name: Copy Mysql 5.7 folder
  copy: 
    src: ./docker/mysql5_7
    dest: ~/docker
    mode: 0755
    
- name: Shut down service
  shell: |
    cd ~/docker/mysql5_7
    docker compose down

- name: Start Mysql 5.7
  shell: |
    cd ~/docker/mysql5_7
    export TZ={{tz}}
    export MYSQL_ROOT_USER={{root_user}}
    export MYSQL_ROOT_PASSWORD={{root_password}}
    export MYSQL_DATABASE={{db}}
    export MYSQL_USER={{user}}
    export MYSQL_PASSWORD={{password}}
    export PORT={{port_export}}
    export NETWORK={{network}}
    export LOG_MAX_SIZE={{log_max_size}}
    export LOG_MAX_FILE={{log_max_file}}
    docker compose up -d