version: '3.8'

services:
  rmq1:
    image: rabbitmq:3-management
    restart: always
    container_name: rmq1
    hostname: rmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - default

  rmq2:
    image: rabbitmq:3-management
    restart: always
    container_name: rmq2
    hostname: rmq2
    depends_on:
      - rmq1
    environment:
      - JOIN_CLUSTER_HOST=rmq1
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - default

  rmq3:
    image: rabbitmq:3-management
    restart: always
    container_name: rmq3
    hostname: rmq3
    depends_on:
      - rmq1
    environment:
      - JOIN_CLUSTER_HOST=rmq1
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - default

  rmq-haproxy:
    image: haproxy:alpine
    restart: always
    container_name: rmq-haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rmq1
      - rmq2
      - rmq3
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - default

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true