---
- name: Copy supabase folder
  copy: 
    src: ./docker/supabase
    dest: ~/docker
    mode: 0755
    
- name: Shut down service
  shell: |
    cd ~/docker/supabase
    docker compose down

- name: Start supabase
  shell: |
    cd ~/docker/supabase
    export SUPABASE_VIRTUAL_HOST={{host}}
    export LOG_VIRTUAL_HOST={{log_host}}
    export LETSENCRYPT_EMAIL={{letsencrypt_email}}
    export NETWORK={{network}}
    export LOG_MAX_SIZE={{log_max_size}}
    export LOG_MAX_FILE={{log_max_file}}
    docker compose up -d