---
- name: Copy docker-db-backup folder
  copy:
    src: ./docker/docker-db-backup
    dest: ~/docker
    mode: 0755

- name: Shut down service
  shell: |
    cd ~/docker/docker-db-backup
    docker compose down

- name: Start docker-db-backup
  shell: |
    cd ~/docker/docker-db-backup
    export TZ={{tz}}
    export BACKUP_JOB_CONCURRENCY={{backup_job_concurrency}}
    export S3_BUCKET={{s3_bucket}}
    export S3_KEY_ID={{s3_key_id}}
    export S3_KEY_SECRET={{s3_key_secret}}
    export S3_REGION={{s3_region}}
    export S3_HOST={{s3_host}}
    export S3_PATH={{s3_path}}
    export DB_HOST={{db_host}}
    export DB_PORT={{db_port}}
    export DB_NAME={{db_name}}
    export DB_USER={{db_user}}
    export DB_PASS={{db_pass}}
    export NETWORK={{network}}
    export LOG_MAX_SIZE={{log_max_size}}
    export LOG_MAX_FILE={{log_max_file}}
    docker compose up -d
