---
- name: Deploy echo service

  hosts: all

  become: true

  vars_files:
    - vars/common.yml
    - vars/echo.yml

  tasks:
    - import_tasks: tasks/echo/start.yml
    - import_tasks: tasks/common/prune.yml
