---
- name: Deploy minio service

  hosts: all

  vars_files:
    - vars/common.yml
    - vars/timezone.yml
    - vars/minio.yml

  tasks:
    - import_tasks: tasks/minio/start.yml
    # - import_tasks: tasks/common/prune.yml
