---
- name: Deploy pgbouncer service

  hosts: all

  vars_files:
    - vars/common.yml
    - vars/timezone.yml

  tasks:
    - import_tasks: tasks/pgbouncer/start.yml
    - import_tasks: tasks/common/prune.yml
