---
- name: Deploy Hazelcast 5 cluster service

  hosts: all

  vars_files:
    - vars/common.yml
    - vars/timezone.yml
    - vars/hazelcast5-cluster.yml

  tasks:
    - import_tasks: tasks/hazelcast5-cluster/start.yml
    # - import_tasks: tasks/common/prune.yml
