---
- name: Deploy Hazelcast cluster service

  hosts: all

  vars_files:
    - vars/common.yml
    - vars/timezone.yml
    - vars/hazelcast.yml

  tasks:
    - import_tasks: tasks/hazelcast-cluster/start.yml
    - import_tasks: tasks/common/prune.yml
