---
- name: Install Nginx Proxy with Dockergen & Let's Encrypt

  hosts: all

  become: true

  gather_facts: yes

  vars_files:
    - vars/nginx.yml

  tasks:
    - import_tasks: tasks/install-nginx.yml
