version: '3.9'
name: novu
services:
  redis:
    container_name: nv-redis
    image: redis
    ports:
      - 6379
    healthcheck:
      test: "bash -c 'redis-cli ping'"
      retries: 5
      interval: 10s
    networks:
      - default
  api:
    image: 'ghcr.io/novuhq/novu/api:0.24.0'
    depends_on:
    #   - mongodb
      - redis
    container_name: nv-api
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_ROOT_URL=${API_ROOT_URL}
      - DISABLE_USER_REGISTRATION=${DISABLE_USER_REGISTRATION}
      - PORT=${API_PORT}
      - FRONT_BASE_URL=${FRONT_BASE_URL}
      - MONGO_URL=${MONGO_URL}
      - MONGO_MIN_POOL_SIZE=${MONGO_MIN_POOL_SIZE}
      - MONGO_MAX_POOL_SIZE=${MONGO_MAX_POOL_SIZE}
      - REDIS_HOST=nv-redis
      - REDIS_PORT=6379
      - REDIS_DB_INDEX=2
      - REDIS_CACHE_SERVICE_HOST=${REDIS_CACHE_SERVICE_HOST}
      - REDIS_CACHE_SERVICE_PORT=${REDIS_CACHE_SERVICE_PORT}
      - S3_LOCAL_STACK=${S3_LOCAL_STACK}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - STORE_ENCRYPTION_KEY=${STORE_ENCRYPTION_KEY}
      - IS_MULTI_TENANCY_ENABLED=${IS_MULTI_TENANCY_ENABLED}
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=${API_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${API_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      # SENTRY_DSN: ${SENTRY_DSN}
      # NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      # NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      - API_CONTEXT_PATH=${API_CONTEXT_PATH}
    ports:
      - 3000
    networks:
      - default
  worker:
    image: 'ghcr.io/novuhq/novu/worker:0.24.3'
    depends_on:
    #   - mongodb
      - redis
    container_name: nv-worker
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
      - MONGO_MAX_POOL_SIZE=${MONGO_MAX_POOL_SIZE}
      - REDIS_HOST=nv-redis
      - REDIS_PORT=6379
      - REDIS_CACHE_SERVICE_HOST=${REDIS_CACHE_SERVICE_HOST}
      - REDIS_CACHE_SERVICE_PORT=${REDIS_CACHE_SERVICE_PORT}
      - S3_LOCAL_STACK=${S3_LOCAL_STACK}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - STORE_ENCRYPTION_KEY=${STORE_ENCRYPTION_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
      # NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      # NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      - BROADCAST_QUEUE_CHUNK_SIZE=${BROADCAST_QUEUE_CHUNK_SIZE}
      - MULTICAST_QUEUE_CHUNK_SIZE=${MULTICAST_QUEUE_CHUNK_SIZE}
      - IS_MULTI_TENANCY_ENABLED=${IS_MULTI_TENANCY_ENABLED}
    networks:
      - default
  ws:
    image: 'ghcr.io/novuhq/novu/ws:0.24.3'
    depends_on:
    #   - mongodb
      - redis
    container_name: nv-ws
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      - PORT=${WS_PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
      - MONGO_MAX_POOL_SIZE=${MONGO_MAX_POOL_SIZE}
      - REDIS_HOST=nv-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      # WS_CONTEXT_PATH: ${WS_CONTEXT_PATH}
      # NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      # NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      - VIRTUAL_PORT=3002
      - VIRTUAL_HOST=${WS_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${WS_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - 3002
    networks:
      - default
  web:
    image: 'ghcr.io/novuhq/novu/web:0.24.3'
    depends_on:
      - api
      - worker
    container_name: nv-web
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      - REACT_APP_API_URL=https://nv-api.kqxs99.net
      - REACT_APP_ENVIRONMENT=${NODE_ENV}
      - REACT_APP_WIDGET_EMBED_PATH=${WIDGET_EMBED_PATH}
      - REACT_APP_DOCKER_HOSTED_ENV=true
      - REACT_APP_WS_URL=${REACT_APP_WS_URL}
      - IS_MULTI_TENANCY_ENABLED=${IS_MULTI_TENANCY_ENABLED}
      - VIRTUAL_PORT=4200
      - VIRTUAL_HOST=${DASH_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${DASH_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - 4200
    networks:
      - default
  widget:
    image: 'ghcr.io/novuhq/novu/widget:0.24.3'
    depends_on:
      - api
      - worker
      - web
    container_name: nv-widget
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      - REACT_APP_API_URL=${API_ROOT_URL}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL}
      - REACT_APP_ENVIRONMENT=${NODE_ENV}
      - WIDGET_CONTEXT_PATH=${WIDGET_CONTEXT_PATH}
      - VIRTUAL_PORT=4500
      - VIRTUAL_HOST=${WIDGET_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${WIDGET_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - 4500
    networks:
      - default
  embed:
    depends_on:
      - widget
    image: 'ghcr.io/novuhq/novu/embed:0.24.3'
    container_name: nv-embed
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'
    environment:
      - WIDGET_URL=${WIDGET_URL}
      # NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      # NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      - VIRTUAL_PORT=4701
      - VIRTUAL_HOST=${EMBED_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${EMBED_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - 4701
    networks:
      - default

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true
# volumes:
#   mongodb: ~