---
- name: Copy browserless folder
  copy:
    src: ./docker/browserless
    dest: ~/docker
    mode: 0755

- name: Shut down service
  shell: |
    cd ~/docker/browserless
    docker compose down

- name: Start browserless
  shell: |
    cd ~/docker/browserless
    export PORT={{port_export}}
    export NETWORK={{network}}
    export LOG_MAX_SIZE={{log_max_size}}
    export LOG_MAX_FILE={{log_max_file}}
    docker compose up -d
