version: '3.8'

networks:
  cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.56.0.0/16
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true

services:
  mysqlmaster:
    hostname: mysqlmaster
    image: garutilorenzo/mysql-gtid-replication:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./grants/:/docker-entrypoint-initdb.d/
      - ./config/master.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysqlmaster:/var/lib/mysql
    networks:
      default:
      cluster:
        ipv4_address: 172.56.0.2

  mysqlslave:
    hostname: mysqlslave
    image: garutilorenzo/mysql-gtid-replication:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_MASTER_HOST: mysqlmaster
      MYSQL_MASTER_USER: root
      MYSQL_MASTER_PASSWORD: password
      MYSQL_REPLICATION_USER: repl
      MYSQL_REPLICATION_PASSWORD: repl
    volumes:
      - ./grants/:/docker-entrypoint-initdb.d/
      - ./config/replica.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysqlslave:/var/lib/mysql
    networks:
      default:
      cluster:
        ipv4_address: 172.56.0.3

  proxysql:
    hostname: proxysql
    image: severalnines/proxysql:latest
    ports:
      - 3306:3306
      - 3307:3307
      - 3308:3308
      - 6032:6032
    volumes:
      - ./config/proxysql.cnf:/etc/proxysql.cnf
      - ./proxysql:/var/lib/proxysql
    command: ['proxysql', '-f', '--reload', '-c', '/etc/proxysql.cnf']
    networks:
      default:
      cluster:
        ipv4_address: 172.56.0.4
    depends_on:
      - mysqlmaster
      - mysqlslave

  heartbeat:
    hostname: heartbeat
    image: garutilorenzo/heartbeat:latest
    networks:
      cluster:
        ipv4_address: 172.56.0.5
    depends_on:
      - proxysql
      - mysqlmaster
      - mysqlslave
    environment:
      PT_MASTER: proxysql
      PT_DATABASE: percona
      PT_USER: super
      PT_PASSWORD: superLuser

  orchestrator:
    hostname: orchestrator
    image: openarkcode/orchestrator:latest
    command:
      - /bin/bash
      - -c
      - |
        sleep 60
        /usr/local/orchestrator/orchestrator -c clusters
        /usr/local/orchestrator/orchestrator -c discover -i mysqlmaster:3306
        /usr/local/orchestrator/orchestrator -c discover -i mysqlslave:3306
        /usr/local/orchestrator/orchestrator http
    volumes:
      - ./config/orchestrator.conf.json:/etc/orchestrator.conf.json
      - ./orchestrator:/app/data
    networks:
      default:
      cluster:
        ipv4_address: 172.56.0.7
    ports:
      - '3000:3000'
