version: '3.8'

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true

x-env-share: &env-share
  PATRONI_RESTAPI_USERNAME: ${PATRONI_RESTAPI_USERNAME:-admin}
  PATRONI_RESTAPI_PASSWORD: ${PATRONI_RESTAPI_PASSWORD:-admin}
  PATRONI_SUPERUSER_USERNAME: ${PATRONI_SUPERUSER_USERNAME:-postgres}
  PATRONI_SUPERUSER_PASSWORD: ${PATRONI_SUPERUSER_PASSWORD:-postgres}
  PATRONI_REPLICATION_USERNAME: ${PATRONI_REPLICATION_USERNAME:-replicator}
  PATRONI_REPLICATION_PASSWORD: ${PATRONI_REPLICATION_PASSWORD:-replicate}
  PATRONI_admin_PASSWORD: ${PATRONI_admin_PASSWORD:-admin}
  PATRONI_admin_OPTIONS: createdb,createrole

services:
  etcd1: &etcd
    image: anvu69/patroni-citus:3.2.2-no-ssl
    environment:
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: tutorial
      ETCD_UNSUPPORTED_ARCH: arm64
    container_name: etcd1
    command: etcd --name etcd1 --initial-advertise-peer-urls http://etcd1:2380
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}

  etcd2:
    <<: *etcd
    container_name: etcd2
    command: etcd --name etcd2 --initial-advertise-peer-urls http://etcd2:2380

  etcd3:
    <<: *etcd
    container_name: etcd3
    command: etcd --name etcd3 --initial-advertise-peer-urls http://etcd3:2380

  haproxy:
    image: anvu69/patroni-citus:3.2.2-no-ssl
    container_name: patroni-citus-haproxy
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    ports:
      - '${PORT:-5000}:5000' # Access to the coorinator primary
      - '5001:5001' # Load-balancing across workers primaries
      - '7001:7000' # stats
    environment: &haproxy_env
      <<: *env-share
      ETCDCTL_ENDPOINTS: http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
      PATRONI_ETCD3_HOSTS: "'etcd1:2379','etcd2:2379','etcd3:2379'"
      PATRONI_SCOPE: ${PATRONI_SCOPE:-demo}
      PATRONI_CITUS_GROUP: 0
      PATRONI_CITUS_DATABASE: citus
    command: haproxy

  # Coordinator
  coord1:
    image: anvu69/patroni-citus:3.2.2-no-ssl
    container_name: coord1
    environment: &coord_env
      <<: *haproxy_env
      PATRONI_NAME: coord1
      PATRONI_CITUS_GROUP: 0
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}

  coord2:
    image: anvu69/patroni-citus:3.2.2-no-ssl
    container_name: coord2
    environment:
      <<: *coord_env
      PATRONI_NAME: coord2
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}

  coord3:
    image: anvu69/patroni-citus:3.2.2-no-ssl
    container_name: coord3
    environment:
      <<: *coord_env
      PATRONI_NAME: coord3
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}

  # Patroni + PostgreSQL + Citus worker nodes (two worker clusters with two nodes each)
  work1-1:
    image: anvu69/patroni-citus:3.2.2-no-ssl
    container_name: work1-1
    environment: &work1_env
      <<: *haproxy_env
      PATRONI_NAME: work1-1
      PATRONI_CITUS_GROUP: 1
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}

  work1-2:
    image: anvu69/patroni-citus:3.2.2-no-ssl
    container_name: work1-2
    environment:
      <<: *work1_env
      PATRONI_NAME: work1-2
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}

  work2-1:
    image: anvu69/patroni-citus:3.2.2-no-ssl
    container_name: work2-1
    environment: &work2_env
      <<: *haproxy_env
      PATRONI_NAME: work2-1
      PATRONI_CITUS_GROUP: 2
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}

  work2-2:
    image: anvu69/patroni-citus:3.2.2-no-ssl
    container_name: work2-2
    environment:
      <<: *work2_env
      PATRONI_NAME: work2-2
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}

volumes:
  coord1_data:
  coord2_data:
  coord3_data:
  work11_data:
  work12_data:
  work21_data:
  work22_data:
