version: '3.8'

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true

services:
  hc1:
    image: hazelcast/hazelcast:3.12.5
    container_name: hc1
    restart: always
    hostname: hc1
    ports:
      - 5701:5701
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MIN_HEAP_SIZE=2g
      - JAVA_OPTS=-Dhazelcast.config=/config/hazelcast.xml
    networks:
      - default