version: '3.8'

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true

services:
  hc51:
    image: hazelcast/hazelcast:5.4
    container_name: hc51
    restart: always
    hostname: hc51
    ports:
      - 15701:5701
    environment:
      - HZ_NETWORK_PUBLICADDRESS=${IP:-0.0.0.0}:15701
      - HZ_CLUSTERNAME=${CLUSTER_NAME}
  hc52:
    image: hazelcast/hazelcast:5.4
    container_name: hc52
    restart: always
    hostname: hc52
    ports:
      - 15702:5701
    environment:
      - HZ_NETWORK_PUBLICADDRESS=${IP:-0.0.0.0}:15702
      - HZ_CLUSTERNAME=${CLUSTER_NAME}
  hc53:
    image: hazelcast/hazelcast:5.4
    container_name: hc53
    restart: always
    hostname: hc53
    ports:
      - 15703:5701
    environment:
      - HZ_NETWORK_PUBLICADDRESS=${IP:-0.0.0.0}:15703
      - HZ_CLUSTERNAME=${CLUSTER_NAME}
  management-center:
    image: hazelcast/management-center:5.4
    container_name: management-center
    restart: always
    ports:
      - 8080
    environment:
      - MC_DEFAULT_CLUSTER=${CLUSTER_NAME}
      - MC_DEFAULT_CLUSTER_MEMBERS=hc51
      - MC_ADMIN_USER=${MC_ADMIN_USER}
      - MC_ADMIN_PASSWORD=${MC_ADMIN_PASSWORD}
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}