version: '2'
services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
    ports:
      - "${HOST_TUN_PORT:-1194}:1194/udp"
        # - "${HOST_CONF_PORT:-80}:8080/tcp"
    environment:
      - DEBUG=1
    #     HOST_ADDR: ${HOST_ADDR:-localhost}
    #     NET_ADAPTER: ${NET_ADAPTER:-eth0}
    #     HOST_TUN_PORT: ${HOST_TUN_PORT:-1194}
    #     HOST_CONF_PORT: ${HOST_CONF_PORT:-80}
    volumes:
      - ./openvpn_data/conf:/etc/openvpn
    restart: always