version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql2017
    restart: always
    ports:
      - '${PORT:-1433}:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=${MSSQL_PID}
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_AGENT_ENABLED=true
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}
    networks:
      - default

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true
