version: '3.8'

services:
  statping:
    container_name: statping
    image: statping/statping
    restart: always
    volumes:
      - ./data:/app
    environment:
      DB_CONN: sqlite
      VIRTUAL_PORT: 8080
      VIRTUAL_PROTO: http
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    ports:
      - 8080

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true