---
- name: Post install
  shell: |
    sleep 5
    docker exec -it proxysql bash -c mysql -h proxysql -P6032 -uradmin -pradmin -e "update global_variables set variable_value='false' where variable_name='admin-hash_passwords';" -e "load admin variables to runtime; save admin variables to disk;" -e "load mysql users to runtime; save mysql users to disk;"
