version: "3.8"

services:
  es:
    image: anvu69/elasticsearch-vietnamese:${STACK_VERSION}
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
    environment:
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - VIRTUAL_PORT=9200
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=${ELASTIC_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${ELASTIC_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    # mem_limit: ${MEM_LIMIT}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --user elastic:${ELASTIC_PASSWORD} -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    restart: always
    depends_on:
      es:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - 5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - VIRTUAL_PORT=5601
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=${KIBANA_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${KIBANA_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true