version: '3.8'

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true

services:
  echo:
    image: hashicorp/http-echo
    ports:
      - 5678
    command: -text="hello world"
    environment:
      - VIRTUAL_PORT=5678
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}