services:
  minio:
    image: minio/minio
    container_name: minio_s3
    ports:
      - 9000
      - 9001
    volumes:
      - ./minio_storage:/data
      - ./minio/certs:/etc/minio/certs
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-root}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password}
      - VIRTUAL_PORT=9001
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    command: server --console-address ":9001" /data
    networks:
      - default

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true
