version: "3.8"

services:
  mysql5_7:
    image: mysql:5.7
    container_name: mysql5_7
    restart: always
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER:-root}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-r00t}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-db}
      - MYSQL_USER=${MYSQL_USER:-user1}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-simpl3}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_bin',
        '--performance_schema=0'
      ]
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "${PORT:-13306}:3306"
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILE:-10}
    networks:
      - default

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true