version: '3.8'

services:
  rmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    ports:
      - '${PORT:-5672}:5672'
    networks:
      - default

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true