version: '3.8'

# services:
#   hc1:
#     image: hazelcast/hazelcast:5.3-slim
#     container_name: hc1
#     restart: always
#     hostname: hc1
#     ports:
#       - 5701:5701
#     volumes:
#       - ./hc1:/opt/hazelcast/persistence
#     environment:
#       - HZ_NETWORK_PUBLICADDRESS=${IP:-0.0.0.0}:5701
#       - HZ_CLUSTERNAME=${CLUSTER_NAME}
#   hc2:
#     image: hazelcast/hazelcast:5.3-slim
#     container_name: hc2
#     restart: always
#     hostname: hc2
#     ports:
#       - 5702:5701
#     volumes:
#       - ./hc2:/opt/hazelcast/persistence
#     environment:
#       - HZ_NETWORK_PUBLICADDRESS=${IP:-0.0.0.0}:5702
#       - HZ_CLUSTERNAME=${CLUSTER_NAME}
#   hc3:
#     image: hazelcast/hazelcast:5.3-slim
#     container_name: hc3
#     restart: always
#     hostname: hc3
#     ports:
#       - 5703:5701
#     environment:
#       - HZ_NETWORK_PUBLICADDRESS=${IP:-0.0.0.0}:5703
#       - HZ_CLUSTERNAME=${CLUSTER_NAME}
#   hc4:
#     image: hazelcast/hazelcast:5.3-slim
#     container_name: hc4
#     restart: always
#     hostname: hc4
#     ports:
#       - 5704:5701
#     volumes:
#       - ./hc4:/opt/hazelcast/persistence
#     environment:
#       - HZ_NETWORK_PUBLICADDRESS=${IP:-0.0.0.0}:5704
#       - HZ_CLUSTERNAME=${CLUSTER_NAME}
#   management-center:
#     image: hazelcast/management-center
#     container_name: hcm
#     ports:
#       - 8080
#       - "8081:8081"
#     environment:
#       - MC_DEFAULT_CLUSTER=${CLUSTER_NAME}
#       - MC_HEALTH_CHECK_ENABLE=true
#       - MC_DEFAULT_CLUSTER_MEMBERS=hc1,hc2,hc3,hc4
#       - MC_ADMIN_USER=${MC_ADMIN_USER}
#       - MC_ADMIN_PASSWORD=${MC_ADMIN_PASSWORD}
#       - VIRTUAL_PORT=8080
#       - VIRTUAL_PROTO=http
#       - VIRTUAL_HOST=${VIRTUAL_HOST}
#       - LETSENCRYPT_HOST=${VIRTUAL_HOST}
#       - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

# networks:
#   default:
#     name: ${NETWORK:-nginx_proxy}
#     external: true

services:
  hc1:
    image: hazelcast/hazelcast:3.12.5
    container_name: hc1
    restart: always
    hostname: hc1
    ports:
      - 5701:5701
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MIN_HEAP_SIZE=2g
      - JAVA_OPTS=-Dhazelcast.config=/config/hazelcast.xml
    # networks:
    #   - default

  # hc2:
  #   image: hazelcast/hazelcast:3.12.5
  #   container_name: hc2
  #   restart: always
  #   hostname: hc2
  #   ports:
  #     - 5702:5701
  #   ulimits:
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   volumes:
  #     - ./config:/config
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - MIN_HEAP_SIZE=2g
  #     - JAVA_OPTS=-Dhazelcast.config=/config/hazelcast.xml
  #   networks:
  #     - default

  # hc3:
  #   image: hazelcast/hazelcast:3.12.5
  #   container_name: hc3
  #   restart: always
  #   hostname: hc3
  #   ports:
  #     - 5703:5701
  #   ulimits:
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   volumes:
  #     - ./config:/config
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - MIN_HEAP_SIZE=2g
  #     - JAVA_OPTS=-Dhazelcast.config=/config/hazelcast.xml
  #   networks:
  #     - default

  # hc4:
  #   image: hazelcast/hazelcast:3.12.5
  #   container_name: hc4
  #   restart: always
  #   hostname: hc4
  #   ports:
  #     - 5704:5701
  #   ulimits:
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   volumes:
  #     - ./config:/config
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - MIN_HEAP_SIZE=2g
  #     - JAVA_OPTS=-Dhazelcast.config=/config/hazelcast.xml
  #   networks:
  #     - default

  # hc5:
  #   image: hazelcast/hazelcast:3.12.5
  #   container_name: hc5
  #   restart: always
  #   hostname: hc5
  #   ports:
  #     - 5705:5701
  #   ulimits:
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   volumes:
  #     - ./config:/config
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - MIN_HEAP_SIZE=2g
  #     - JAVA_OPTS=-Dhazelcast.config=/config/hazelcast.xml
  #   networks:
  #     - default

  # management-center:
  #   image: hazelcast/management-center:3.12.5
  #   container_name: hmc
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - MIN_HEAP_SIZE=2g
  #     - JAVA_OPTS=-Dhazelcast.mc.disk.usage.mode=block -Dhazelcast.mc.disk.usage.limit=2GB
  #   networks:
  #     - default
