version: "3.8"

services:
  hc1:
    image: hazelcast/hazelcast:5.4.0-SNAPSHOT-slim
    container_name: hc1
    hostname: hc1
    ports:
      - 5701:5701
    environment:
      - HZ_CLUSTERNAME=${CLUSTER_NAME}
  hc2:
    image: hazelcast/hazelcast:5.4.0-SNAPSHOT-slim
    container_name: hc2
    hostname: hc2
    ports:
      - 5701
    environment:
      - HZ_CLUSTERNAME=${CLUSTER_NAME}
  hc3:
    image: hazelcast/hazelcast:5.4.0-SNAPSHOT-slim
    container_name: hc3
    hostname: hc3
    ports:
      - 5701
    environment:
      - HZ_CLUSTERNAME=${CLUSTER_NAME}
  hc4:
    image: hazelcast/hazelcast:5.4.0-SNAPSHOT-slim
    container_name: hc4
    hostname: hc4
    ports:
      - 5701
    environment:
      - HZ_CLUSTERNAME=${CLUSTER_NAME}
  management-center:
    image: hazelcast/management-center
    container_name: hcm
    ports:
      - 8080
      - "8081:8081"
    environment:
      - MC_DEFAULT_CLUSTER=${CLUSTER_NAME}
      - MC_HEALTH_CHECK_ENABLE=true
      - MC_DEFAULT_CLUSTER_MEMBERS=hc1,hc2,hc3,hc4
      - MC_ADMIN_USER=${MC_ADMIN_USER}
      - MC_ADMIN_PASSWORD=${MC_ADMIN_PASSWORD}
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

networks:
  default:
    name: ${NETWORK:-nginx_proxy}
    external: true